# Generated by Django 4.1.7 on 2023-02-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_vegetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='photos/vegetable')),
            ],
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
