# Generated by Django 4.1.7 on 2023-02-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
